name: VLR Daily Scraper

on:
  schedule:
    # Roda todo dia às 06:00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch: 

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar Dependências
        run: pip install -r requirements.txt

      - name: Rodar o Scraper com Retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10    # Tempo máximo de cada tentativa
          max_attempts: 3        # Tenta até 3 vezes se der erro
          retry_wait_seconds: 60 # Espera 1 minuto entre as tentativas
          command: python src/auto_scrapper.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}